# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'fileutils'

default_platform(:ios)

$ignore_file_path = '.xcovignore'

before_all do
	FileUtils.rm_rf("./UnitTestsReport")
	FileUtils.rm_rf("./CodeCoverageReport")
end

platform :ios do
	desc "Run tests and create a unit-test report"

	lane :unit_tests do
  		run_tests(
			package_path: ".",
			scheme: "DragonAnnouncement",
			only_testing: "DragonAnnouncementTests",
			clean: true,
			code_coverage: true,
			device: "iPhone 15 Pro",
			result_bundle: true,
			skip_build: true,
			xcodebuild_formatter: 'xcbeautify -qq --is-ci --renderer github-actions',
			output_types: 'junit',
			output_directory: "./fastlane/UnitTestsReport"
		)

		xcov(
			is_swift_package: true,
			scheme: "DragonAnnouncement",
			#only_project_targets: true,
			output_directory: "./fastlane/CodeCoverageReport"
			#minimum_coverage_percentage: 80.0
  		)
	end

end
