name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
  
# Limit only the latest workflow created to run
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Update dependencies
      run: bundle install --path vendor/bundle

    - name: Install build log formatter
      run: brew install xcbeautify
      
    - name: Run Unit Tests
      run: bundle exec fastlane ios unit_tests
